### PR TITLE
Upgrade to NativeScript 5.0.0 and added support for Angular

### PR DESCRIPTION
**Pull request by VladimirAmiorkov**
This PR introduces:

- Compatibility with NativeScript 5.0.0
- Support for NativeScript Angular project
- Compatibility with Ahead of Time Compilation of NativeScript Angular project
- New Angular Demo for testing purposes
- Refactored type definitions
- New npm scripts for packing, publishing and running the repositories demos for easier plugin contribution 

# Related issues
#12 

@bradmartin @burkeholland I would appreciate if you can take a look at this PR and if possible to merge and release a new version to npm.

### CODE REVIEW

**Comment by tjvantoll** [comment]
Thanks @VladimirAmiorkov! This is now merged and published.

Just fyi `npm run pack` froze for me when copying the `src` folder, which was a bit odd. When I ran the pack and publish scripts manually though everything worked fine. No big deal, but I thought I’d note that for future reference.

**Comment by VladimirAmiorkov** [comment]
Hi @tjvantoll ,

Thank you. I will take a look at the `npm run pack` command I have not used it also so I will fix it.

**Comment by burkeholland** [comment]
Thanks, @VladimirAmiorkov!

I love that you all have kept this project going. It's literally my only contribution to humanity.

**Comment by VladimirAmiorkov** [comment]
@burkeholland No problem, glad to have helped. I doubt that dude :)

**Pull request merged**
