### PR TITLE
Make package compatible with webpack.

### PR DESCRIPTION
**Pull request by fmsaraujo**

### CODE REVIEW

**Comment by svzi** [comment]
Could this PR please be merged?

**Comment by simonox** [comment]
@burkeholland Please merge this PR. It solves the webpack issue: https://github.com/burkeholland/nativescript-statusbar/issues/6

**Comment by Burgov** [comment]
@burkeholland ping

**Comment by tjvantoll** [comment]
Merged with 6cd74420bbf558a4263648a4c2ef0dba4d64f44a.

**Pull request merged**
